---
# tasks file for firewall-config
- name: open httpd port
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
- name: open mysql port
  firewalld:
    port: 3306/tcp
    permanent: yes
    state: enabled
- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded