---
# tasks file for moodle-config
- name: Download Moodle
  get_url:
    url: https://download.moodle.org/download.php/direct/stable311/moodle-latest-311.tgz
    dest: /tmp
    mode: '0777'
- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/moodle-latest-311.tgz
    dest: /var/www/html
    remote_src: yes
- name: Allow apache to modify files in /var/www/html/moodle
  sefcontext:
    target: '/var/www/html/moodle(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present

- name: Apply new SELinux file context to filesystem
  command: restorecon -irv /var/www/html/moodle

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /var/www/html/moodle
    owner: nobody
    group: nobody
    mode: '0777'

- name: Creates directory
  file:
    path: /var/www/moodledata
    state: directory
    owner: nobody
    group: nobody
    mode: '0777'
- name: Allow apache to modify files in /var/www/html/moodle
  sefcontext:
    target: '/var/www/moodledata(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present

- name: Apply new SELinux file context to filesystem
  command: restorecon -irv /var/www/moodledata


